import pandas as pd
from io import BytesIO
from pathlib import Path
import os

def merge_files(second_file, output_filename):
    try:
        # Load the first file generated by mise_a_jour.py
        first_file_path = Path(os.path.dirname(__file__)) / 'data' / 'fichier_mise_a_jour.xlsx'
        if not first_file_path.exists():
            raise FileNotFoundError(f"The file {first_file_path} is missing. Please ensure it is generated by mise_a_jour.py.")

        first_df = pd.read_excel(first_file_path)

        # Load the second uploaded file
        second_df = pd.read_excel(second_file)

        # Ensure both DataFrames have a common column for merging (e.g., 'Référence')
        if 'Référence' not in first_df.columns or 'Référence' not in second_df.columns:
            raise ValueError("Both files must contain the 'Référence' column for merging.")

        # Merge the two DataFrames on 'Référence'
        merged_df = pd.merge(first_df, second_df, on='Référence', how='outer')

        # Export the merged DataFrame to an Excel file in memory
        output = BytesIO()
        with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
            merged_df.to_excel(writer, index=False, sheet_name='Merged_Data')

        # Return the output file
        output.seek(0)
        return output

    except Exception as e:
        print(f"Error during merging: {e}")
        raise